# Generated by Django 5.2.12 on 2026-03-11 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='camera_id',
            field=models.CharField(blank=True, default='', help_text='Channel ID or camera ID from the NVR', max_length=100),
        ),
        migrations.AlterField(
            model_name='nvr',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Optional admin notes'),
        ),
        migrations.AlterField(
            model_name='nvr',
            name='url',
            field=models.CharField(help_text='Base URL of NVR web interface (e.g. http://192.168.1.100:8080)', max_length=500),
        ),
    ]
