# Generated by Django 4.2.9 on 2026-03-11 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_camera_camera_id_alter_nvr_notes_alter_nvr_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='camera_ip',
            field=models.GenericIPAddressField(blank=True, help_text='Direct IP of the camera if available', null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='rtsp_url',
            field=models.CharField(blank=True, default='', help_text='RTSP stream URL (e.g. rtsp://user:pass@ip:port/ch1)', max_length=1000),
        ),
    ]
